### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by GitauHarrison** [AlvaroIsrael/monokai-dark-green#1]
Consider changing your overview to fix the minor typos you have:

... I really have no idea why. ~~Then I have~~ I decided to ~~chage~~ change it from yellow to green ... Then I made this dark theme so others, also annoyed by ~~taht~~ that yellow color, could also benefit from it ...

**Comment by AlvaroIsrael** [comment]
Nice! I'll fix this in the next days, because i would also have to publish a new version of the theme in the Store. But I will leave this Issue opened until i fix it! Thanks!
