### ISSUE TITLE
Bright white background behind text.

### ISSUE THREAD

**Issue by shawn-yee** [AlvaroIsrael/monokai-dark-green#3]
I am not sure whether it is my local setting problem.

It shows a bright white background in some places, which makes words unable to read.

<img width="432" alt="截屏2021-10-26 下午5 48 26" src="https://user-images.githubusercontent.com/66560386/138854227-161c3ccd-bfef-496f-ba84-d4db888238a2.png">
<img width="874" alt="截屏2021-10-26 下午5 48 03" src="https://user-images.githubusercontent.com/66560386/138854279-304cb330-2ee3-4bd8-8da3-d43dbcb7d93c.png">

**Comment by AlvaroIsrael** [comment]
I will look into it, and see if I can fix it. If it's a local problem only you are having I'll also reply. Thanks for filling this issue up.

**Comment by AlvaroIsrael** [comment]
@shawn-yee It does not seem its your local settings, here I am also getting a gray background, ill try to fix this.

**Comment by shawn-yee** [comment]
```json
"workbench.colorCustomizations": {
	...
    "selection.background": "#006400",
	...
}

**Comment by AlvaroIsrael** [comment]
Nice ill have to publish a new version with the fix!
